 controller_list:
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_left_joint1
      - panda_left_joint2
      - panda_left_joint3
      - panda_left_joint4
      - panda_left_joint5
      - panda_left_joint6
      - panda_left_joint7
