position_joint_position_controller:
    type: franka_ros_controllers/PositionJointPositionController
    joint_names:
        - panda_right_joint1
        - panda_right_joint2
        - panda_right_joint3
        - panda_right_joint4
        - panda_right_joint5
        - panda_right_joint6
        - panda_right_joint7
    joint_position_limit:
        lower:
            panda_right_joint1: -2.8973  # rad
            panda_right_joint2: -1.7628  # rad
            panda_right_joint3: -2.8973  # rad
            panda_right_joint4: -3.0718  # rad
            panda_right_joint5: -2.8973  # rad
            panda_right_joint6: -0.0175  # rad
            panda_right_joint7: -2.8973  # rad
        upper:
            panda_right_joint1: 2.8973  # rad
            panda_right_joint2: 1.7628  # rad
            panda_right_joint3: 2.8973  # rad
            panda_right_joint4: -0.0698 # rad
            panda_right_joint5: 2.8973  # rad
            panda_right_joint6: 3.7525  # rad
            panda_right_joint7: 2.8973  # rad
    publish_rate: 30.0

velocity_joint_velocity_controller:
    type: franka_ros_controllers/VelocityJointVelocityController
    joint_names:
        - panda_right_joint1
        - panda_right_joint2
        - panda_right_joint3
        - panda_right_joint4
        - panda_right_joint5
        - panda_right_joint6
        - panda_right_joint7
    publish_rate: 30.0
    joint_velocity_limit:
        panda_right_joint1: 2.1750  # rad / sec
        panda_right_joint2: 2.1750  # rad / sec
        panda_right_joint3: 2.1750  # rad / sec
        panda_right_joint4: 2.1750  # rad / sec
        panda_right_joint5: 2.6100  # rad / sec
        panda_right_joint6: 2.6100  # rad / sec
        panda_right_joint7: 2.6100  # rad / sec

effort_joint_impedance_controller:
    type: franka_ros_controllers/EffortJointImpedanceController
    arm_id: panda_right
    joint_names:
        - panda_right_joint1
        - panda_right_joint2
        - panda_right_joint3
        - panda_right_joint4
        - panda_right_joint5
        - panda_right_joint6
        - panda_right_joint7
    k_gains: # if changing the default values, remember to change in the cfg file as well
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0
    coriolis_factor: 1.0
    joint_position_limit:
        lower:
            panda_right_joint1: -2.8973  # rad
            panda_right_joint2: -1.7628  # rad
            panda_right_joint3: -2.8973  # rad
            panda_right_joint4: -3.0718  # rad
            panda_right_joint5: -2.8973  # rad
            panda_right_joint6: -0.0175  # rad
            panda_right_joint7: -2.8973  # rad
        upper:
            panda_right_joint1: 2.8973  # rad
            panda_right_joint2: 1.7628  # rad
            panda_right_joint3: 2.8973  # rad
            panda_right_joint4: -0.0698 # rad
            panda_right_joint5: 2.8973  # rad
            panda_right_joint6: 3.7525  # rad
            panda_right_joint7: 2.8973  # rad
    joint_velocity_limit:
        panda_right_joint1: 2.1750  # rad / sec
        panda_right_joint2: 2.1750  # rad / sec
        panda_right_joint3: 2.1750  # rad / sec
        panda_right_joint4: 2.1750  # rad / sec
        panda_right_joint5: 2.6100  # rad / sec
        panda_right_joint6: 2.6100  # rad / sec
        panda_right_joint7: 2.6100  # rad / sec

effort_joint_position_controller:
    type: franka_ros_controllers/EffortJointPositionController
    arm_id: panda_right
    joint_names:
        - panda_right_joint1
        - panda_right_joint2
        - panda_right_joint3
        - panda_right_joint4
        - panda_right_joint5
        - panda_right_joint6
        - panda_right_joint7
    k_gains:
        - 1200.0
        - 1000.0
        - 1000.0
        - 800.0
        - 300.0
        - 200.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    publish_rate: 30.0
    joint_position_limit:
        lower:
            panda_right_joint1: -2.8973  # rad
            panda_right_joint2: -1.7628  # rad
            panda_right_joint3: -2.8973  # rad
            panda_right_joint4: -3.0718  # rad
            panda_right_joint5: -2.8973  # rad
            panda_right_joint6: -0.0175  # rad
            panda_right_joint7: -2.8973  # rad
        upper:
            panda_right_joint1: 2.8973  # rad
            panda_right_joint2: 1.7628  # rad
            panda_right_joint3: 2.8973  # rad
            panda_right_joint4: -0.0698 # rad
            panda_right_joint5: 2.8973  # rad
            panda_right_joint6: 3.7525  # rad
            panda_right_joint7: 2.8973  # rad

effort_joint_torque_controller:
    type: franka_ros_controllers/EffortJointTorqueController
    arm_id: panda_right
    compensate_coriolis: false
    publish_rate: 30.0
    joint_names:
        - panda_right_joint1
        - panda_right_joint2
        - panda_right_joint3
        - panda_right_joint4
        - panda_right_joint5
        - panda_right_joint6
        - panda_right_joint7
    joint_effort_limit:
        panda_right_joint1: 87  # Nm
        panda_right_joint2: 87  # Nm
        panda_right_joint3: 87  # Nm
        panda_right_joint4: 87  # Nm
        panda_right_joint5: 12  # Nm
        panda_right_joint6: 12  # Nm
        panda_right_joint7: 12  # Nm

